# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget Pack & Publish

on:
  push:
    branches: [ "main" ]
    paths:
    - 'src/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/JBrLloyd/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Pack
      run: dotnet pack -c Release --output ${{ github.workspace }}/nuget

    - name: Publish Package
      run: dotnet nuget push ${{ github.workspace }}/nuget/*.nupkg --skip-duplicate
